FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copy built files
COPY . .
RUN npm run build

# use Nginx to serve static files
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]
