# Build stage
FROM node:20 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copy built files
COPY . .

# Accept build-time variables
ARG VITE_API_URI
ENV VITE_API_URI=$VITE_API_URI

RUN npm run build

# Production Stage

# use Nginx to serve static files
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]
