services:
  postgres-db:
    image: postgres:13
    container_name: postgres-db-prod
    restart: always
    env_file:
      - server/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-photo_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-photo_pw}
      POSTGRES_DB: ${POSTGRES_DB:-photo_metadata_db}
    ports:
      - "5433:5432"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    networks:
      - test-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "photo_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./server
      dockerfile: dockerfile
    container_name: backend
    depends_on:
      postgres-db:
        condition: service_healthy  # wait for database
    env_file:
      - server/.env.test
    ports:
      - "4002:4002"
    volumes:
      - ./server:/app
    networks:
      - test-net

  frontend:
    build:
      context: ./client
      dockerfile: dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "5174:80"
    volumes:
      - ./client:/app
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - test-net

volumes:
  postgres-db-data:

networks:
  test-net:
