FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install --only=production

# Copy the built server files
COPY . .

# Compile TypeScript Code
RUN npx tsc

# Generate Prisma client
RUN npx prisma generate

EXPOSE 4002

# Run database migrations before starting the server
CMD ["sh", "-c", "npx prisma migrate deploy && node ./dist/index.js"]
