name: Deployment

on:
    workflow_run:
        workflows: ["Continuous Integration"]
        types:
            - completed

jobs:
    deploy:
        name: Deploy to Production
        runs-on: ubuntu-latest
        environment: production
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and Push Server Image
              run: |
                docker build -t aw-gallery/server:latest ./server
                docker tag aw-gallery/server:latest aw-gallery/server:${{ github.sha }}
                docker push aw-gallery/server:latest
                docker push aw-gallery/backend:${{ github.sha }}

            - name: Build and Push Server Image
              run: |
                docker build -t aw-gallery/server:latest ./server
                docker tag aw-gallery/server:latest aw-gallery/server:${{ github.sha }}
                docker push aw-gallery/server:latest
                docker push aw-gallery/backend:${{ github.sha }}
